### ISSUE TITLE
Are they still working ?

### ISSUE THREAD

**Issue by vexcited** [retoheusser/happy-headers#6]
Been struggling on an error 400 when calling `/api/vonage/data-exchange`.

When I fill the signature and device-id with the ones I can get from my network requests, it works, but when I use the signature and device-id from happy-headers, it fails.

My timezone is also `Europe/Paris` and of course I gave every other headers (`bereal-platform`, `bereal-os-version`, ...)

Any idea? Thanks !

**Comment by retoheusser** [comment]
I can confirm that this library is still working on the friends feed endpoint, I use it daily.
However I haven't tried it on your mentioned vonage endpoint. What I know is that the signature is computed from the timezone and the device id, so these 3 headers must be used in conjunction all from happy-headers.

**Comment by vexcited** [comment]
Not sure why but it was not working on the vonage endpoints, so I reversed the algorithm myself and found a way to get the signatures, thanks anyway !
